#!/bin/bash
#
# FastCarPlay Build Script for Raspberry Pi 5 (ARM64)
# Builds the CarPlay/Android Auto receiver engine
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CARPLAY_DIR="$SCRIPT_DIR/carplay_engine"
CONF_DIR="$CARPLAY_DIR/conf"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║       FastCarPlay Build Script for Raspberry Pi 5             ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check if running on Raspberry Pi
check_platform() {
    if [ -f /proc/device-tree/model ]; then
        MODEL=$(cat /proc/device-tree/model)
        echo "📟 Detected: $MODEL"
    else
        echo "⚠️  Warning: Could not detect Raspberry Pi model"
        echo "   This script is optimized for Raspberry Pi 5"
    fi
    echo ""
}

# Install dependencies
install_dependencies() {
    echo "📦 Installing build dependencies..."
    echo "   This may take a few minutes on first run..."
    echo ""
    
    sudo apt update
    
    # Build dependencies
    sudo apt install -y \
        build-essential \
        xxd \
        libsdl2-dev \
        libsdl2-ttf-dev \
        libavformat-dev \
        libavcodec-dev \
        libavutil-dev \
        libswscale-dev \
        libusb-1.0-0-dev \
        libssl-dev
    
    # Runtime dependencies
    sudo apt install -y \
        ffmpeg \
        libsdl2-2.0-0 \
        libsdl2-ttf-2.0-0 \
        libusb-1.0-0 \
        libssl3
    
    echo ""
    echo "✅ Dependencies installed successfully"
    echo ""
}

# Setup USB permissions for Carlinkit dongle
setup_usb_permissions() {
    echo "🔌 Setting up USB permissions for CarPlay dongle..."
    
    # Create udev rule for common Carlinkit vendor IDs
    UDEV_RULE='SUBSYSTEM=="usb", ATTRS{idVendor}=="1314", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="1234", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="154b", MODE="0666"'
    
    echo "$UDEV_RULE" | sudo tee /etc/udev/rules.d/51-carplay-dongle.rules > /dev/null
    
    # Add current user to plugdev group
    sudo usermod -aG plugdev "$USER" 2>/dev/null || true
    
    # Reload udev rules
    sudo udevadm control --reload-rules
    sudo udevadm trigger
    
    echo "✅ USB permissions configured"
    echo "   You may need to log out and back in for group changes to take effect"
    echo ""
}

# Build FastCarPlay
build_carplay() {
    echo "🔨 Building FastCarPlay..."
    echo ""
    
    if [ ! -d "$CARPLAY_DIR" ]; then
        echo "❌ Error: carplay_engine directory not found"
        echo "   Please ensure FastCarPlay is cloned to $CARPLAY_DIR"
        exit 1
    fi
    
    cd "$CARPLAY_DIR"
    
    # Clean previous build
    echo "   Cleaning previous build..."
    make clean 2>/dev/null || true
    
    # Build release version
    echo "   Compiling release build (this may take a few minutes)..."
    make release
    
    # Check if build succeeded
    if [ -f "$CARPLAY_DIR/out/app" ]; then
        echo ""
        echo "✅ FastCarPlay built successfully!"
        echo "   Executable: $CARPLAY_DIR/out/app"
    else
        echo ""
        echo "❌ Build failed - executable not found"
        exit 1
    fi
    echo ""
}

# Create configuration directory and default settings
setup_configuration() {
    echo "⚙️  Setting up configuration..."
    
    mkdir -p "$CONF_DIR"
    
    # Copy sample settings if not exists
    if [ ! -f "$CONF_DIR/settings.txt" ]; then
        cat > "$CONF_DIR/settings.txt" << 'EOF'
# FastCarPlay Settings - Raspberry Pi 5 with 7" Touchscreen
# Auto-generated by build_carplay.sh

# Display settings for 7" touchscreen (800x480)
width = 800
height = 480
source-fps = 30
fps = 30
fullscreen = true
cursor = false

# Dongle settings - adjust if your dongle has different IDs
# Use lsusb to find your vendor/product ID (convert hex to decimal)
# vendor-id = 4884
# product-id = 5408

# Enable encryption for newer dongles (2024+)
encryption = false

# Connection settings
autoconnect = true
weak-charge = true
left-hand-drive = true
night-mode = 2

# WiFi settings
wifi-5 = true
bluetooth-audio = false
mic-type = 1

# Android Auto settings
android-dpi = 140
android-resolution = 1
android-media-delay = 300

# Performance settings optimized for Pi 5
font-size = 24
vsync = false
hw-decode = true
fast-render-scale = true
video-buffer-size = 32
audio-buffer-size = 32
audio-buffer-wait = 2
audio-buffer-wait-call = 8
audio-fade = 0.3

# Audio driver (pipewire is recommended for Pi 5)
# audio-driver = pipewire

# Named pipe for key commands
key-pipe-path = /tmp/fastcarplay_pipe

# Logging (disable in production for better performance)
logging = false
EOF
        echo "   Created default settings at $CONF_DIR/settings.txt"
    else
        echo "   Settings file already exists, skipping..."
    fi
    
    echo "✅ Configuration ready"
    echo ""
}

# Create named pipe for key commands
create_pipe() {
    echo "📡 Creating named pipe for key commands..."
    
    PIPE_PATH="/tmp/fastcarplay_pipe"
    if [ ! -p "$PIPE_PATH" ]; then
        mkfifo "$PIPE_PATH" 2>/dev/null || true
        chmod 666 "$PIPE_PATH" 2>/dev/null || true
    fi
    
    echo "✅ Named pipe ready at $PIPE_PATH"
    echo ""
}

# Print final instructions
print_instructions() {
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║                    BUILD COMPLETE! 🎉                        ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "To start CarPlay manually:"
    echo "  cd $CARPLAY_DIR"
    echo "  ./out/app ./conf/settings.txt"
    echo ""
    echo "Or use the web interface:"
    echo "  1. Start the car stereo system: ./start.sh"
    echo "  2. Open http://localhost:5000/carplay"
    echo "  3. Click 'Start CarPlay'"
    echo ""
    echo "Connect your Carlinkit dongle and your iPhone/Android phone!"
    echo ""
    echo "Troubleshooting:"
    echo "  - Check dongle is detected: lsusb | grep -i carlin"
    echo "  - Verify USB permissions: ls -la /dev/bus/usb/*/*"
    echo "  - Check logs: journalctl -f"
    echo ""
}

# Main execution
main() {
    check_platform
    
    # Parse arguments
    case "${1:-all}" in
        deps|dependencies)
            install_dependencies
            ;;
        usb|permissions)
            setup_usb_permissions
            ;;
        build)
            build_carplay
            setup_configuration
            create_pipe
            ;;
        config)
            setup_configuration
            create_pipe
            ;;
        all|*)
            install_dependencies
            setup_usb_permissions
            build_carplay
            setup_configuration
            create_pipe
            print_instructions
            ;;
    esac
}

main "$@"

